apiVersion: v1
kind: Service
metadata:
  name: sample-go-app-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sample
  sessionAffinity: None
  type: NodePort